apiVersion: 1
datasources:
  - name: SolarBI PostgreSQL
    uid: solarbi-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: ${PGUSER}
    isDefault: true
    jsonData:
      database: ${PGDATABASE}
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: ${PGPASSWORD}
